### PR TITLE
Merge ci into master to fix failing CI due to pip upgrade

### PR DESCRIPTION
**Pull request by RedFantom**
`pip` has changed its behaviour as a module. Since `pip==10.0.0`, the internal method `main` is now no longer exposed by default, but it is hidden in the submodule `_internal`, so `pip._internal.main`. The team developing `pip` has had quite a lot of discussion on the subject (see `#4798`, `#5080` and `#5149` for just a few examples), but it has been removed, and thus this will serve as a work-around for the time being that functions sufficiently well enough.

### CODE REVIEW

**Comment by Akuli** [comment]
You can still invoke pip without relying on `_implementation_details` like this:

```python3
import runpy
import sys

sys.argv[1:] = ['install', '--upgrade', 'ttkthemes']    # or anything else you want
runpy.run_module('pip', run_name='__main__')
```

**Comment by RedFantom** [comment]
The reason `pip.main` was deprecated, is, as far as I know, is because it is not thread-safe. However, if I run `runpy.run_module` with the `__main__` as `run_name`, then my Python interpreter quits after execution (even when given arguments, on Python 2.7.13 64-bit, Ubuntu 17.04). I think this is by design, as the runpy module is actually what makes `python -m pip` possible. I cannot find any information on how this could be disabled.

However, for now, at least, I would really prefer to have working CI. I will leave this branch in existence for future changes that may make use of the method you suggested, @Akuli .

**Comment by Akuli** [comment]
You can `except SystemExit as e:` if you don't want it to quit, and then check `if e.code == 0` to see if everything succeeded. Pip calls `sys.exit()` for some reason, and runpy simply doesn't catch that for you.

Of course, future versions of pip don't necessarily `sys.exit()`. Python exits with status 0 by default, so if the `except SystemExit` block doesn't run, everything succeeded.

**Comment by Akuli** [comment]
A correction: `sys.exit()` and `sys.exit(0)` both mean success; passing anything else to `sys.exit(  )` means error. For some reason, `sys.exit()` sets `e.code` to `None` and `sys.exit(0)` sets it to `0`, so the check should look like `if e.code in {0, None}:`.

**Pull request merged**
