### PR TITLE
Merge equilux into master to include equilux theme

### PR DESCRIPTION
**Pull request by RedFantom**
It has taken painstakingly selecting each and every correct image file from the [equilux theme repository](https://github.com/ddnexus/equilux-theme) and modifying the arc theme file to support the different theme as well as some GIMP image operations, but it is now finally functional: The `equilux` theme:
screenshot

### CODE REVIEW

**Comment by RedFantom** [comment]
Today clearly is CI problem day. The `macOS` builds for Travis-CI are stalled because of issues, and the `AppVeyor` builds are sporadically having issues connecting to PyPI.

**Comment by Akuli** [comment]
Looks awesome :+1:

**Comment by RedFantom** [comment]
It does, doesn't it? There are still issues with the `Notebook` widget though :disappointed: . I'm holding off merging until I've got those sorted out.

**Comment by RedFantom** [comment]
It is derived from [`materia`](https://github.com/nana-4/materia-theme) (which sure does sound like a material design theme), but currently I have only ported over the `equilux` theme, so only the dark version. `materia` does look really nice, so perhaps I'll do that one in the future as well, but for now I really first need to fix the `Notebook` widget on this theme.

**Comment by RedFantom** [comment]
This branch has now been rebased upon the master branch.

**Pull request merged**
