### PR TITLE
Fix "Unsupported Platform error" (issue #34)

### PR DESCRIPTION
**Pull request by maicol07**
I think I've found how to solve #34 . It should work with all the compilers, such as cx_freeze and pyinstaller.

### CODE REVIEW

**Comment by RedFantom** [comment]
Note to self: AppVeyor CI is failing because `pip` has deprecated the `pip.main` function in `pip==10.0.1`.

**Comment by Akuli** [comment]
I'm kind of surprised. If this really fixes everything, that's great... :D

**Comment by RedFantom** [comment]
Merged. Thank you @maicol07 !

**Comment by maicol07** [comment]
No problem! 👍

**Comment by Akuli** [comment]
When fixing this `setup.py` for my pull request, I kinda wondered why it did some magic with `__file__` instead of relying on the current working directory. I guess I should have asked... :)

**Pull request merged**
